server:
  port: 8033
spring:
  data:
    mongodb:
      URI: mongodb://localhost:27017/MarketBC
    redis:
      port: 6379
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka