server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asolanot94/B35_Project_Final.git
          searchPaths: Config-Data
          username: asolanot94
          password: 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

  security:
    user:
      name: root
      password: s3cr3t